/* GNU AFFERO GENERAL PUBLIC LICENSE  Version 3 (C)2023 */
package de.unimarburg.diz.nexuspathotofhir.model;

public enum ReportDocType {
    UNKNOWN,
    MAIN_REPORT,
    CORRECTION1,
    CORRECTION2,
    CORRECTION3,

    CORRECTION4,
    CORRECTION5,
    CORRECTION6,

    ADDITION1,
    ADDITION2,
    ADDITION3,
    ADDITION4,
    ADDITION5,
    ADDITION6,
    ADDITION7,
    ADDITION8,
    ADDITION9,
    ADDITION10
}
