spring:
  jmx:
    enabled: true
  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-location: file://${SSL_TRUST_STORE_LOCATION_INTERNAL:/opt/kafka-streams-template/ssl/truststore.jks}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-location: file://${SSL_KEY_STORE_LOCATION_INTERNAL:/opt/kafka-streams-template/ssl/keystore.jks}
      key-store-password: ${SSL_KEY_STORE_PASSWORD}

  cloud:
      function:
        definition: processPathoSpecimen;processPathoReport
      stream:
        bindings:
          processPathoSpecimen-in-0:
            destination: patho-specimen
          processPathoSpecimen-out-0:
            destination: idat-patho-specimen
          processPathoReport-in-0:
            destination: patho-report
          processPathoReport-out-0:
            destination: idat-patho-report
        kafka:
          streams:
            binder:
              functions:
                processPathoSpecimen:
                  applicationId: nexus-patho-specimen-to-fhir
                processPathoReport:
                  applicationId: nexus-patho-report-to-fhir
              configuration:
                compression.type: gzip
                max.request.size: 5242880
                spring.json.use.type.headers: "false"
fhir:
  systems:
    serviceRequestId: "https://your-local-system/pathology/serviceRequestId"
    diagnosticReportId: "https://your-local-system/pathology/diagnosticReportId"
    observationId: "https://your-local-system/pathology/observationId"
    patientId: "https://your-local-system/pathology/patientId"
    encounterId: "https://your-local-system/pathology/encounterId"
    assignerId: "https://your-local-system/pathology/assignerId"
    assignerCode: "https://your-local-system/pathology/assignerCode"
    specimenRequestId: "https://your-local-system/pathology/specimenRequestId"
    diagnosticFindingId: "https://your-local-system/pathology/diagnosticFindingId"
    diagnosticFindingGrouperId: "https://your-local-system/pathology/diagnosticFindingGrouperId"
    specimenContainer: "https://your-local-system/pathology/specimenContainer"
    specimenId: "https://your-local-system/pathology/specimenId"
    performerId: "https://your-local-system/pathology/performerId"
mapping:
  location:
    specimenType: "mappings/specimenType.csv"
    specimenExtractionMethod: "mappings/specimenExtractionMethod.csv"
    specimenContainerType: "mappings/specimenContainerType.csv"
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true

logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.nexuspathotofhir: debug
