
fhir:
  systems:
    serviceRequestId: "https://your-local-system/pathology/serviceRequestId"
    diagnosticReportId: "https://your-local-system/pathology/diagnosticReportId"
    observationId: "https://your-local-system/pathology/observationId"
    patientId: "https://your-local-system/pathology/patientId"
    encounterId: "https://your-local-system/pathology/encounterId"
    assignerId: "https://your-local-system/pathology/assignerId"
    assignerCode: "https://your-local-system/pathology/assignerCode"
    specimenRequestId: "https://your-local-system/pathology/specimenRequestId"

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true

logging:
  level:
    org.springframework.kafka.config: debug
    de.unimarburg.diz.nexuspathotofhir: debug
