name: 'Run Tests'

on:
  push:
    branches: [ 'master' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: c-hive/gha-npm-cache@v1
        
      - name: setup npm deps
        run: npm install

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.12.0

      - name: Execute tests
        run: ./gradlew test

  integrationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.12.0

      - name: Execute integration tests
        run: ./gradlew integrationTest
